name: Build Hugo Image

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: 🐋 Login to Github Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Hugo
      uses: klakegg/actions-hugo@1.0.0
      
    - name: Push to GitHub Registry
      run: docker push ghcr.io/axemorgan/wedding-site:${{ github.sha }}
